[tools]
"github:fish-shell/fish-shell" = "latest"
neovim = "latest"
lazygit = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
zoxide = "latest"
bat = "latest"
delta = "latest"
node = "lts"    # LazyVim/mason needs it

[settings]
experimental = true
